### ISSUE TITLE
Waarom

### ISSUE THREAD

**Issue by Paultje52** [Qyther/Griefbot#1]
Een vraagje,

waarom heb je deze griefbot gemaakt? Het bied nul meerwaarden, sterker nog, hiermee verpest je heel veel servers. Mensen werken hard om mooie discord servers te maken en dan komen er mensen aan die code's van het internet af halen om die servers te verpesten.

Laat ik dit even in perspectief brengen: Stel je voor, jij hebt een server waar 1000den mensen op zitten. En je hebt een custom bot. De token van de bot wordt geleaked. En dan ben je opeens al je mensen kwijt, uit het niets zijn ze allemaal weg. Dat wil je toch niet?

Je moet niet willen dat mensen hun tijd kwijt zijn aan praktisch gezien niets. Je moet toch niet willen dat **jij** verantwoordelijk bent aan het verlies van van een grote discord. Dan ben je echt niet goed in je hoofd.

Daarom is mijn vraag: Hoe krijg je het in je hoofd om code te schrijven die puur en alleen bedoeld is om andere mensen te ruïneren? Ben je dan echt zo dom? 

Verspil je tijd niet aan "dome" projecten, besteed je tijd aan projecten die je op een portfolio kan zetten. Dingen waar je trots op kan zijn. Of ben je trots op jezelf dat je er voor hebt kunnen zorgen dat discord servers worden geruïneerd door jou? Want dan ben je echt ziek in je hoofd.

**Comment by Paultje52** [comment]
Ik weet dat je nog steeds github gebruikt en dat je dit hebt gezien. Erg jammer dat je niet eens het respect kan opbrengen om te reageren...

**Comment by Paultje52** [comment]
Oja, zodat je t weet, k heb t gerapporteerd bij github, net zoals een ander project dat je had gemaakt met dezelfde bedoeling...

**Comment by Qyther** [comment]
Dit zie ik nu voor de eerste keer nu dat ik mijn repo's aan het checken ben. Het hele idee dat jij hebt rondom Discord servers is een beetje verdraaid. Ten eerste is het heel onwaarschijnlijk dat de token van een bot van een server met duizenden leden publiek gemaakt wordt, ten tweede ben ik niet direct verantwoordelijk voor het verlies van een grote Discord server omdat ik niet degene ben die de code uitvoer, ten derde neem je jezelf een beetje te serieus met je "respect opbrengen" want ik ben jou helemaal geen respect verschuldigd, ten vierde zijn er honderden andere bots die precies hetzelfde doen en als jij held wil gaan uitvoeren om een paar Discord servers te verdedigen, die 99% procent van de tijd toch waardeloos en geen toevoeging aan de maatschappij zijn, dan zou ik je aanraden om vooral het internet af te gaan en bij elke bot doen wat je nu doet. Foei. Ik kan mij echt niet inleven in jou aangezien jij zo erg wild wordt over een stukje code wat "bedoeld is om andere mensen te ruïneren". Zwaar leven heb jij dan als Discord jouw hele wezen is.
